用户指南
------------

这部分文档主要介绍了Flask的背景，然后对于Flask的web开发做了一个一步一
步的要点指示.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   reqcontext
   blueprints
   shell
   patterns/index
   deploying/index
   becomingbig

API 参考
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

其它事项
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   upgrading
   changelog
   license
